- name: 'HashToken Login'
  uriPattern: 'neos/sentry/show-parameters'
  defaults:
    '@package':    'Netlogix.Sentry'
    '@controller': 'EncryptedPayload'
    '@action':     'decrypt'
    '@format':     'html'
  appendExceedingArguments: true
  httpMethods: ['GET']

- name: 'Content Security Policy'
  uriPattern: 'api/csp-report'
  defaults:
    '@package':    'Netlogix.Sentry'
    '@controller': 'ContentSecurityPolicy'
    '@action':     'index'
    '@format':     'json'
  appendExceedingArguments: true
  httpMethods: ['POST']
