Neos:
  Flow:
    http:
      middlewares:
        'nlxSentryContentSecurityPolicy':
          position: 'before dispatch'
          middleware: 'Netlogix\Sentry\ContentSecurityPolicy\ContentSecurityPolicyMiddleware'
