Neos:
  Flow:
    http:
      middlewares:
        'nlxSentryContentSecurityPolicy':
          position: 'before dispatch'
          middleware: 'Netlogix\Sentry\Http\Middleware\ContentSecurityPolicyMiddleware'
